name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: winxp/unreal-universe-builder:latest
    steps:
      - uses: actions/checkout@v1
        with:
          lfs: true
      - name: Build with Gradle
        run: ./gradlew build